"""Host-neutral, fail-closed adaptation contracts (HANDOFF M4/G3)."""

from capability_exchange.adaptation.allowlist import (
    ALLOWED_OPERATIONS,
    AllowedOperation,
    OperationAssessment,
    OperationRequest,
    RefusalCode,
    assess_operation,
    canonical_target,
)
from capability_exchange.adaptation.approval import (
    AdaptationApproval,
    ApprovalAuthority,
    ApprovalExpiredError,
    ApprovalMismatchError,
    ApprovalReplayError,
    IssuedApproval,
)
from capability_exchange.adaptation.contract import (
    REQUIRED_GUARANTEES,
    Guarantee,
    MutationContract,
    OperationKind,
)
from capability_exchange.adaptation.incidents import IncidentKind, IncidentRecord
from capability_exchange.adaptation.preview import (
    AdaptationPreview,
    PreviewDriftError,
    PreviewMismatchError,
    assert_preview_current,
    build_preview,
)
from capability_exchange.adaptation.receipt import (
    TransactionReceipt,
    read_receipt,
    write_receipt,
)
from capability_exchange.adaptation.recovery import (
    RecoveryConflictError,
    RecoveryPoint,
    RecoveryUnavailableError,
    create_recovery_point,
    restore_absent_target,
    validate_recovery_point,
)
from capability_exchange.adaptation.transaction import (
    AutomationHardStoppedError,
    InjectedCrash,
    JournalState,
    RecoveryFailedError,
    TransactionConflictError,
    TransactionEngine,
    TransactionFailedError,
    TransactionJournal,
    TransactionResult,
    UndoConflictError,
    UndoResult,
    UndoStatus,
)
from capability_exchange.adaptation.verification import (
    VerificationResult,
    VerificationVerdict,
    verify_created_skill,
)

__all__ = [
    "ALLOWED_OPERATIONS",
    "REQUIRED_GUARANTEES",
    "AllowedOperation",
    "AdaptationApproval",
    "AdaptationPreview",
    "AutomationHardStoppedError",
    "ApprovalAuthority",
    "ApprovalExpiredError",
    "ApprovalMismatchError",
    "ApprovalReplayError",
    "Guarantee",
    "IncidentKind",
    "IncidentRecord",
    "InjectedCrash",
    "JournalState",
    "MutationContract",
    "OperationAssessment",
    "OperationKind",
    "OperationRequest",
    "IssuedApproval",
    "PreviewDriftError",
    "PreviewMismatchError",
    "RecoveryConflictError",
    "RecoveryPoint",
    "RecoveryUnavailableError",
    "RecoveryFailedError",
    "RefusalCode",
    "TransactionReceipt",
    "TransactionConflictError",
    "TransactionEngine",
    "TransactionFailedError",
    "TransactionJournal",
    "TransactionResult",
    "UndoConflictError",
    "UndoResult",
    "UndoStatus",
    "VerificationResult",
    "VerificationVerdict",
    "assess_operation",
    "assert_preview_current",
    "build_preview",
    "canonical_target",
    "create_recovery_point",
    "read_receipt",
    "restore_absent_target",
    "validate_recovery_point",
    "verify_created_skill",
    "write_receipt",
]
